title: Foveated Animations for Efficient Crowd Simulation
description: Foveating agent animations in a scene to reduce computation power of crowds without impacting user experience.
theme: minima


domain: "lfirsl.github.io"
url: "https://lfirsl.github.io"
baseurl: "/foveated-animations-project/"

show_downloads: false
github:
  is_project_page: false